apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: c1
    image: nginx
    ports:
      - containerPort: 80

  - name: c2
    image: tomcat
    ports:
      - containerPort: 8080

