apiVersion: v1
kind: Pod
metadata:
 name: mysql-server
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpassword
    - name: MYSQL_DATABASE
      value: cka
    - name: MYSQL_USER
      value: user
    - name: MYSQL_PASSWORD
      value: password
    image: mysql
    name: server
    ports:
     - containerPort: 3306
