apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secondpod
  name: secondpod
spec:
  containers:
  - image: nginx
    name: secondpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
