apiVersion: batch/v1
kind: Job
metadata:
  name: print-hello
spec:
  template:
    metadata:
      labels:
        job: hello
      spec:
        containers:
        - image: alpine
          name: print-hello
          command: ['sh','-c','echo hello && sleep 5']
        restartPolicy: Never
