apiVersion: v1
kind: Pod
metadata:
 name: volume-pod
spec:
 containers:
 - name: rnd
   image: alpine
   command: ["/bin/sh", "-c","shuf -n 1 -i 0-1000 >> /opt/number.out && sleep 10"]
   volumeMounts:
   - name: number-storage
     mountPath: /opt
 volumes:
  - name: number-storage
    hostPath:
      path: /tmp/data
      type: DirectoryOrCreate
