apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: preferred-affinity-pod
spec:
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
  affinity: 
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference: 
          matchExpressions:
          - key: color
            operator: In
            values:
            - purple


