apiVersion: v1
kind: Pod
metadata:
  name: required-affinity-pod
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: color
              operator: In
              values:
              - green
              - red    
